import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import ProviderStore from "./ProviderStore";
import { useSelector } from "react-redux";
import { RootState } from '@/redux/store';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <ProviderStore>
          <Navbar />
          <div className="mt-28 w-full container">
            {children}
          </div>
          <Footer />
        </ProviderStore>
      </body>
    </html>
  );
}
